swagger: '2.0'
info:
  title: Cart API
  version: 1.0.0
host: localhost:5080
basePath: /api
schemes:
  - http
paths:
  /view-cart:
    get:
      summary: Retrieve the cart for the current user
      description: |
        Retrieves the cart for the user identified by the X-User-Id header.
      produces:
        - application/json
      parameters:
        - name: X-User-Id
          in: header
          description: The ID of the user whose cart is being requested
          required: true
          type: string
      responses:
        '200':
          description: Cart data retrieved successfully
          schema:
            $ref: '#/definitions/Cart'
        '404':
          description: Cart not found
definitions:
  CartItem:
    type: object
    properties:
      productId:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: number
      imageUrl:
        type: string
  Cart:
    type: object
    properties:
      userId:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/CartItem'
      total:
        type: number
      modifiedOn:
        type: string
